import { SourceLocation, Token, TokenType, Keyword } from "../../../src/lexer"

export default [
    new Token(TokenType.Reserved, "CREATE", { keyword: Keyword.CREATE, location: new SourceLocation(0, 1, 0)}),
    new Token(TokenType.Identifier, "TRIGGER", { keyword: Keyword.TRIGGER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(6, 1, 6)})], location: new SourceLocation(7, 1, 7)}),
    new Token(TokenType.Identifier, "update_customer_address", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(14, 1, 14)})], location: new SourceLocation(15, 1, 15)}),
    new Token(TokenType.Reserved, "UPDATE", { keyword: Keyword.UPDATE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(38, 1, 38)})], location: new SourceLocation(39, 1, 39)}),
    new Token(TokenType.Identifier, "OF", { keyword: Keyword.OF, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(45, 1, 45)})], location: new SourceLocation(46, 1, 46)}),
    new Token(TokenType.Identifier, "address", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(48, 1, 48)})], location: new SourceLocation(49, 1, 49)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(56, 1, 56)})], location: new SourceLocation(57, 1, 57)}),
    new Token(TokenType.Identifier, "customers", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(59, 1, 59)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(69, 1, 69)}), new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(70, 1, 70)})], location: new SourceLocation(60, 1, 60)}),
    new Token(TokenType.Identifier, "BEGIN", { keyword: Keyword.BEGIN, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(76, 2, 6)})], location: new SourceLocation(71, 2, 1)}),
    new Token(TokenType.Reserved, "UPDATE", { keyword: Keyword.UPDATE, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(77, 3, 1)})], location: new SourceLocation(79, 3, 3)}),
    new Token(TokenType.Identifier, "orders", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(85, 3, 9)})], location: new SourceLocation(86, 3, 10)}),
    new Token(TokenType.Reserved, "SET", { keyword: Keyword.SET, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(92, 3, 16)})], location: new SourceLocation(93, 3, 17)}),
    new Token(TokenType.Identifier, "address", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(96, 3, 20)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(104, 3, 28)})], location: new SourceLocation(97, 3, 21)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(105, 3, 29)}),
    new Token(TokenType.Identifier, "new", { keyword: Keyword.NEW, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(106, 3, 30)})], location: new SourceLocation(107, 3, 31)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(110, 3, 34)}),
    new Token(TokenType.Identifier, "address", { location: new SourceLocation(111, 3, 35)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(118, 3, 42)})], location: new SourceLocation(119, 3, 43)}),
    new Token(TokenType.Identifier, "customer_name", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(124, 3, 48)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(138, 3, 62)})], location: new SourceLocation(125, 3, 49)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(139, 3, 63)}),
    new Token(TokenType.Identifier, "old", { keyword: Keyword.OLD, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(140, 3, 64)})], location: new SourceLocation(141, 3, 65)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(144, 3, 68)}),
    new Token(TokenType.Identifier, "name", { keyword: Keyword.NAME, location: new SourceLocation(145, 3, 69)}),
    new Token(TokenType.SemiColon, ";", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(150, 3, 74)})], location: new SourceLocation(149, 3, 73)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, location: new SourceLocation(151, 4, 1)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(155, 4, 5)})], location: new SourceLocation(154, 4, 4)}),
    new Token(TokenType.Reserved, "CREATE", { keyword: Keyword.CREATE, location: new SourceLocation(156, 5, 1)}),
    new Token(TokenType.Identifier, "TRIGGER", { keyword: Keyword.TRIGGER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(162, 5, 7)})], location: new SourceLocation(163, 5, 8)}),
    new Token(TokenType.Identifier, "cust_addr_chng", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(170, 5, 15)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(185, 5, 30)})], location: new SourceLocation(171, 5, 16)}),
    new Token(TokenType.Identifier, "INSTEAD", { keyword: Keyword.INSTEAD, location: new SourceLocation(186, 6, 1)}),
    new Token(TokenType.Identifier, "OF", { keyword: Keyword.OF, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(193, 6, 8)})], location: new SourceLocation(194, 6, 9)}),
    new Token(TokenType.Reserved, "UPDATE", { keyword: Keyword.UPDATE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(196, 6, 11)})], location: new SourceLocation(197, 6, 12)}),
    new Token(TokenType.Identifier, "OF", { keyword: Keyword.OF, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(203, 6, 18)})], location: new SourceLocation(204, 6, 19)}),
    new Token(TokenType.Identifier, "cust_addr", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(206, 6, 21)})], location: new SourceLocation(207, 6, 22)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(216, 6, 31)})], location: new SourceLocation(217, 6, 32)}),
    new Token(TokenType.Identifier, "customer_address", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(219, 6, 34)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(236, 6, 51)})], location: new SourceLocation(220, 6, 35)}),
    new Token(TokenType.Identifier, "BEGIN", { keyword: Keyword.BEGIN, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(242, 7, 6)})], location: new SourceLocation(237, 7, 1)}),
    new Token(TokenType.Reserved, "UPDATE", { keyword: Keyword.UPDATE, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(243, 8, 1)})], location: new SourceLocation(245, 8, 3)}),
    new Token(TokenType.Identifier, "customer", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(251, 8, 9)})], location: new SourceLocation(252, 8, 10)}),
    new Token(TokenType.Reserved, "SET", { keyword: Keyword.SET, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(260, 8, 18)})], location: new SourceLocation(261, 8, 19)}),
    new Token(TokenType.Identifier, "cust_addr", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(264, 8, 22)})], location: new SourceLocation(265, 8, 23)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(274, 8, 32)}),
    new Token(TokenType.Identifier, "NEW", { keyword: Keyword.NEW, location: new SourceLocation(275, 8, 33)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(278, 8, 36)}),
    new Token(TokenType.Identifier, "cust_addr", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(288, 8, 46)})], location: new SourceLocation(279, 8, 37)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, preskips: [new Token(TokenType.WhiteSpace, "   ", { location: new SourceLocation(289, 9, 1)})], location: new SourceLocation(292, 9, 4)}),
    new Token(TokenType.Identifier, "cust_id", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(297, 9, 9)})], location: new SourceLocation(298, 9, 10)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(305, 9, 17)}),
    new Token(TokenType.Identifier, "NEW", { keyword: Keyword.NEW, location: new SourceLocation(306, 9, 18)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(309, 9, 21)}),
    new Token(TokenType.Identifier, "cust_id", { location: new SourceLocation(310, 9, 22)}),
    new Token(TokenType.SemiColon, ";", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(318, 9, 30)})], location: new SourceLocation(317, 9, 29)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, location: new SourceLocation(319, 10, 1)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(323, 10, 5)})], location: new SourceLocation(322, 10, 4)}),
    new Token(TokenType.Reserved, "CREATE", { keyword: Keyword.CREATE, location: new SourceLocation(324, 11, 1)}),
    new Token(TokenType.Identifier, "TEMP", { keyword: Keyword.TEMP, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(330, 11, 7)})], location: new SourceLocation(331, 11, 8)}),
    new Token(TokenType.Identifier, "TRIGGER", { keyword: Keyword.TRIGGER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(335, 11, 12)})], location: new SourceLocation(336, 11, 13)}),
    new Token(TokenType.Identifier, "ex1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(343, 11, 20)})], location: new SourceLocation(344, 11, 21)}),
    new Token(TokenType.Identifier, "AFTER", { keyword: Keyword.AFTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(347, 11, 24)})], location: new SourceLocation(348, 11, 25)}),
    new Token(TokenType.Reserved, "INSERT", { keyword: Keyword.INSERT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(353, 11, 30)})], location: new SourceLocation(354, 11, 31)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(360, 11, 37)})], location: new SourceLocation(361, 11, 38)}),
    new Token(TokenType.Identifier, "main", { keyword: Keyword.MAIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(363, 11, 40)})], location: new SourceLocation(364, 11, 41)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(368, 11, 45)}),
    new Token(TokenType.Identifier, "tab1", { location: new SourceLocation(369, 11, 46)}),
    new Token(TokenType.Identifier, "BEGIN", { keyword: Keyword.BEGIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(373, 11, 50)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(379, 11, 56)}), new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(380, 11, 57)})], location: new SourceLocation(374, 11, 51)}),
    new Token(TokenType.Reserved, "INSERT", { keyword: Keyword.INSERT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(381, 12, 1)})], location: new SourceLocation(383, 12, 3)}),
    new Token(TokenType.Reserved, "INTO", { keyword: Keyword.INTO, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(389, 12, 9)})], location: new SourceLocation(390, 12, 10)}),
    new Token(TokenType.Identifier, "sample", { keyword: Keyword.SAMPLE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(394, 12, 14)})], location: new SourceLocation(395, 12, 15)}),
    new Token(TokenType.Reserved, "DEFAULT", { keyword: Keyword.DEFAULT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(401, 12, 21)})], location: new SourceLocation(402, 12, 22)}),
    new Token(TokenType.Reserved, "VALUES", { keyword: Keyword.VALUES, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(409, 12, 29)})], location: new SourceLocation(410, 12, 30)}),
    new Token(TokenType.SemiColon, ";", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(417, 12, 37)})], location: new SourceLocation(416, 12, 36)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, location: new SourceLocation(418, 13, 1)}),
    new Token(TokenType.SemiColon, ";", { eos: true, location: new SourceLocation(421, 13, 4)})
]
