import { SourceLocation, Token, TokenType, Keyword } from "../../../src/lexer"

export default [
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(0, 1, 0)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(6, 1, 6)})], location: new SourceLocation(7, 1, 7)}),
    new Token(TokenType.Operator, "+", { location: new SourceLocation(8, 1, 8)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(9, 1, 9)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(10, 1, 10)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(11, 1, 11)}),
    new Token(TokenType.Comma, ",", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(13, 1, 13)})], location: new SourceLocation(12, 1, 12)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(14, 1, 14)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(15, 1, 15)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(16, 1, 16)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(17, 1, 17)}),
    new Token(TokenType.Operator, "/", { location: new SourceLocation(18, 1, 18)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(19, 1, 19)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(20, 1, 20)})], location: new SourceLocation(21, 1, 21)}),
    new Token(TokenType.Comma, ",", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(24, 1, 24)})], location: new SourceLocation(23, 1, 23)}),
    new Token(TokenType.Operator, "+", { location: new SourceLocation(25, 1, 25)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(26, 1, 26)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(27, 1, 27)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(28, 1, 28)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(29, 1, 29)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(30, 1, 30)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(31, 1, 31)})], location: new SourceLocation(32, 1, 32)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(34, 1, 34)})], location: new SourceLocation(35, 1, 35)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(38, 1, 38)})], location: new SourceLocation(37, 1, 37)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(39, 2, 1)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(45, 2, 7)})], location: new SourceLocation(46, 2, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(48, 2, 10)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(53, 2, 15)})], location: new SourceLocation(49, 2, 11)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(54, 2, 16)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(61, 2, 23)})], location: new SourceLocation(55, 2, 17)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(62, 2, 24)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(63, 2, 25)})], location: new SourceLocation(64, 2, 26)}),
    new Token(TokenType.Identifier, "sample", { keyword: Keyword.SAMPLE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(68, 2, 30)})], location: new SourceLocation(69, 2, 31)}),
    new Token(TokenType.RightParen, ")", { location: new SourceLocation(75, 2, 37)}),
    new Token(TokenType.Reserved, "GROUP", { keyword: Keyword.GROUP, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(76, 2, 38)})], location: new SourceLocation(77, 2, 39)}),
    new Token(TokenType.Identifier, "BY", { keyword: Keyword.BY, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(82, 2, 44)})], location: new SourceLocation(83, 2, 45)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(85, 2, 47)})], location: new SourceLocation(86, 2, 48)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(89, 2, 51)})], location: new SourceLocation(88, 2, 50)}),
    new Token(TokenType.Identifier, "WITH", { keyword: Keyword.WITH, location: new SourceLocation(90, 3, 1)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(94, 3, 5)})], location: new SourceLocation(95, 3, 6)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(96, 3, 7)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(99, 3, 10)})], location: new SourceLocation(97, 3, 8)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(100, 3, 11)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(101, 3, 12)}),
    new Token(TokenType.Identifier, "s", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(107, 3, 18)})], location: new SourceLocation(108, 3, 19)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(109, 3, 20)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(110, 3, 21)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(111, 3, 22)})], location: new SourceLocation(112, 3, 23)}),
    new Token(TokenType.Identifier, "sample", { keyword: Keyword.SAMPLE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(116, 3, 27)})], location: new SourceLocation(117, 3, 28)}),
    new Token(TokenType.Identifier, "s", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(123, 3, 34)})], location: new SourceLocation(124, 3, 35)}),
    new Token(TokenType.RightParen, ")", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(126, 3, 37)})], location: new SourceLocation(125, 3, 36)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(133, 4, 7)})], location: new SourceLocation(127, 4, 1)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(134, 4, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(135, 4, 9)})], location: new SourceLocation(136, 4, 10)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(140, 4, 14)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(142, 4, 16)})], location: new SourceLocation(141, 4, 15)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, location: new SourceLocation(143, 5, 1)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(148, 5, 6)})], location: new SourceLocation(149, 5, 7)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(150, 5, 8)}),
    new Token(TokenType.Identifier, "col1", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(155, 5, 13)})], location: new SourceLocation(151, 5, 9)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(156, 5, 14)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(157, 5, 15)})], location: new SourceLocation(158, 5, 16)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(159, 5, 17)})], location: new SourceLocation(160, 5, 18)}),
    new Token(TokenType.Reserved, "NOT", { keyword: Keyword.NOT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(163, 5, 21)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(167, 5, 25)})], location: new SourceLocation(164, 5, 22)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(168, 5, 26)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(169, 5, 27)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(170, 5, 28)}),
    new Token(TokenType.Identifier, "col2", { location: new SourceLocation(171, 5, 29)}),
    new Token(TokenType.Reserved, "NOT", { keyword: Keyword.NOT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(175, 5, 33)})], location: new SourceLocation(176, 5, 34)}),
    new Token(TokenType.Identifier, "LIKE", { keyword: Keyword.LIKE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(179, 5, 37)})], location: new SourceLocation(180, 5, 38)}),
    new Token(TokenType.String, "'%x%'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(184, 5, 42)})], location: new SourceLocation(185, 5, 43)}),
    new Token(TokenType.Reserved, "OR", { keyword: Keyword.OR, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(190, 5, 48)})], location: new SourceLocation(191, 5, 49)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(193, 5, 51)})], location: new SourceLocation(194, 5, 52)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(195, 5, 53)}),
    new Token(TokenType.Identifier, "col2", { location: new SourceLocation(196, 5, 54)}),
    new Token(TokenType.Reserved, "IS", { keyword: Keyword.IS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(200, 5, 58)})], location: new SourceLocation(201, 5, 59)}),
    new Token(TokenType.Reserved, "NULL", { keyword: Keyword.NULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(203, 5, 61)})], location: new SourceLocation(204, 5, 62)}),
    new Token(TokenType.RightParen, ")", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(209, 5, 67)})], location: new SourceLocation(208, 5, 66)}),
    new Token(TokenType.Reserved, "ORDER", { keyword: Keyword.ORDER, location: new SourceLocation(210, 6, 1)}),
    new Token(TokenType.Identifier, "BY", { keyword: Keyword.BY, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(215, 6, 6)})], location: new SourceLocation(216, 6, 7)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(218, 6, 9)})], location: new SourceLocation(219, 6, 10)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(220, 6, 11)}),
    new Token(TokenType.Identifier, "col3", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(225, 6, 16)})], location: new SourceLocation(221, 6, 12)}),
    new Token(TokenType.Reserved, "LIMIT", { keyword: Keyword.LIMIT, location: new SourceLocation(226, 7, 1)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(231, 7, 6)})], location: new SourceLocation(232, 7, 7)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(234, 7, 9)})], location: new SourceLocation(233, 7, 8)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(241, 8, 7)})], location: new SourceLocation(235, 8, 1)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(242, 8, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(243, 8, 9)})], location: new SourceLocation(244, 8, 10)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(248, 8, 14)})], location: new SourceLocation(249, 8, 15)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(250, 8, 16)}),
    new Token(TokenType.Identifier, "main", { keyword: Keyword.MAIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(251, 8, 17)})], location: new SourceLocation(252, 8, 18)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(256, 8, 22)}),
    new Token(TokenType.Identifier, "b", { location: new SourceLocation(257, 8, 23)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(258, 8, 24)})], location: new SourceLocation(259, 8, 25)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(260, 8, 26)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(261, 8, 27)})], location: new SourceLocation(262, 8, 28)}),
    new Token(TokenType.Reserved, "as", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(263, 8, 29)})], location: new SourceLocation(264, 8, 30)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(266, 8, 32)})], location: new SourceLocation(267, 8, 33)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(268, 8, 34)})], location: new SourceLocation(269, 8, 35)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(274, 8, 40)})], location: new SourceLocation(275, 8, 41)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(276, 8, 42)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(278, 8, 44)})], location: new SourceLocation(277, 8, 43)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(279, 8, 45)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(280, 8, 46)})], location: new SourceLocation(281, 8, 47)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(282, 8, 48)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(283, 8, 49)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(284, 8, 50)})], location: new SourceLocation(285, 8, 51)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(288, 8, 54)})], location: new SourceLocation(289, 8, 55)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(290, 8, 56)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(292, 8, 58)})], location: new SourceLocation(291, 8, 57)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(293, 8, 59)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(294, 8, 60)})], location: new SourceLocation(295, 8, 61)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(296, 8, 62)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(297, 8, 63)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(298, 8, 64)})], location: new SourceLocation(299, 8, 65)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(302, 8, 68)})], location: new SourceLocation(303, 8, 69)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(304, 8, 70)}),
    new Token(TokenType.Identifier, "y", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(306, 8, 72)})], location: new SourceLocation(305, 8, 71)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(307, 8, 73)}),
    new Token(TokenType.Numeric, "0", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(308, 8, 74)})], location: new SourceLocation(309, 8, 75)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(311, 8, 77)})], location: new SourceLocation(310, 8, 76)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(318, 9, 7)})], location: new SourceLocation(312, 9, 1)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(319, 9, 8)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(320, 9, 9)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(321, 9, 10)}),
    new Token(TokenType.Identifier, "TRUE", { keyword: Keyword.TRUE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(322, 9, 11)})], location: new SourceLocation(323, 9, 12)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(327, 9, 16)}),
    new Token(TokenType.Identifier, "FALSE", { keyword: Keyword.FALSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(328, 9, 17)})], location: new SourceLocation(329, 9, 18)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(334, 9, 23)}),
    new Token(TokenType.Reserved, "NULL", { keyword: Keyword.NULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(335, 9, 24)})], location: new SourceLocation(336, 9, 25)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(340, 9, 29)}),
    new Token(TokenType.Reserved, "CURRENT_TIME", { keyword: Keyword.CURRENT_TIME, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(341, 9, 30)})], location: new SourceLocation(342, 9, 31)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(354, 9, 43)}),
    new Token(TokenType.Reserved, "CURRENT_DATE", { keyword: Keyword.CURRENT_DATE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(355, 9, 44)})], location: new SourceLocation(356, 9, 45)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(368, 9, 57)}),
    new Token(TokenType.Reserved, "CURRENT_TIMESTAMP", { keyword: Keyword.CURRENT_TIMESTAMP, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(369, 9, 58)})], location: new SourceLocation(370, 9, 59)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(387, 9, 76)}),
    new Token(TokenType.String, "'aaa'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(388, 9, 77)})], location: new SourceLocation(389, 9, 78)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(394, 9, 83)}),
    new Token(TokenType.Identifier, "\"aaa\"", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(395, 9, 84)})], location: new SourceLocation(396, 9, 85)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(401, 9, 90)}),
    new Token(TokenType.Blob, "x'53514C697465'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(402, 9, 91)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(418, 9, 107)})], location: new SourceLocation(403, 9, 92)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(420, 9, 109)})], location: new SourceLocation(419, 9, 108)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(421, 10, 1)}),
    new Token(TokenType.BindVariable, "?1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(427, 10, 7)})], location: new SourceLocation(428, 10, 8)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(430, 10, 10)}),
    new Token(TokenType.BindVariable, "?", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(431, 10, 11)})], location: new SourceLocation(432, 10, 12)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(433, 10, 13)}),
    new Token(TokenType.BindVariable, ":param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(434, 10, 14)})], location: new SourceLocation(435, 10, 15)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(441, 10, 21)}),
    new Token(TokenType.BindVariable, "@param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(442, 10, 22)})], location: new SourceLocation(443, 10, 23)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(449, 10, 29)}),
    new Token(TokenType.BindVariable, "$param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(450, 10, 30)})], location: new SourceLocation(451, 10, 31)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(458, 10, 38)})], location: new SourceLocation(457, 10, 37)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(459, 11, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(465, 11, 7)})], location: new SourceLocation(466, 11, 8)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(470, 11, 12)})], location: new SourceLocation(471, 11, 13)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(472, 11, 14)})], location: new SourceLocation(473, 11, 15)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(477, 11, 19)})], location: new SourceLocation(478, 11, 20)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(479, 11, 21)})], location: new SourceLocation(480, 11, 22)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(484, 11, 26)})], location: new SourceLocation(485, 11, 27)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(488, 11, 30)})], location: new SourceLocation(489, 11, 31)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(492, 11, 34)})], location: new SourceLocation(493, 11, 35)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(494, 11, 36)})], location: new SourceLocation(495, 11, 37)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(499, 11, 41)})], location: new SourceLocation(500, 11, 42)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(505, 11, 47)})], location: new SourceLocation(504, 11, 46)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(506, 12, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(512, 12, 7)})], location: new SourceLocation(513, 12, 8)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(517, 12, 12)})], location: new SourceLocation(518, 12, 13)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(519, 12, 14)})], location: new SourceLocation(520, 12, 15)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(524, 12, 19)})], location: new SourceLocation(525, 12, 20)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(526, 12, 21)})], location: new SourceLocation(527, 12, 22)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(531, 12, 26)})], location: new SourceLocation(532, 12, 27)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(535, 12, 30)})], location: new SourceLocation(536, 12, 31)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(540, 12, 35)})], location: new SourceLocation(541, 12, 36)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(542, 12, 37)})], location: new SourceLocation(543, 12, 38)}),
    new Token(TokenType.String, "'b'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(547, 12, 42)})], location: new SourceLocation(548, 12, 43)}),
    new Token(TokenType.Reserved, "ELSE", { keyword: Keyword.ELSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(551, 12, 46)})], location: new SourceLocation(552, 12, 47)}),
    new Token(TokenType.String, "'c'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(556, 12, 51)})], location: new SourceLocation(557, 12, 52)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(560, 12, 55)})], location: new SourceLocation(561, 12, 56)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(564, 12, 59)})], location: new SourceLocation(565, 12, 60)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(566, 12, 61)})], location: new SourceLocation(567, 12, 62)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(571, 12, 66)})], location: new SourceLocation(572, 12, 67)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(577, 12, 72)})], location: new SourceLocation(576, 12, 71)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(578, 13, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(584, 13, 7)})], location: new SourceLocation(585, 13, 8)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(589, 13, 12)})], location: new SourceLocation(590, 13, 13)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(594, 13, 17)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(596, 13, 19)})], location: new SourceLocation(595, 13, 18)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(597, 13, 20)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(598, 13, 21)})], location: new SourceLocation(599, 13, 22)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(600, 13, 23)})], location: new SourceLocation(601, 13, 24)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(605, 13, 28)})], location: new SourceLocation(606, 13, 29)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(609, 13, 32)})], location: new SourceLocation(610, 13, 33)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(613, 13, 36)})], location: new SourceLocation(614, 13, 37)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(616, 13, 39)})], location: new SourceLocation(617, 13, 40)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(618, 13, 41)})], location: new SourceLocation(619, 13, 42)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(623, 13, 46)})], location: new SourceLocation(624, 13, 47)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(629, 13, 52)})], location: new SourceLocation(628, 13, 51)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(630, 14, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(636, 14, 7)})], location: new SourceLocation(637, 14, 8)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(641, 14, 12)})], location: new SourceLocation(642, 14, 13)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(646, 14, 17)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(648, 14, 19)})], location: new SourceLocation(647, 14, 18)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(649, 14, 20)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(650, 14, 21)})], location: new SourceLocation(651, 14, 22)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(652, 14, 23)})], location: new SourceLocation(653, 14, 24)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(657, 14, 28)})], location: new SourceLocation(658, 14, 29)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(661, 14, 32)})], location: new SourceLocation(662, 14, 33)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(666, 14, 37)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(668, 14, 39)})], location: new SourceLocation(667, 14, 38)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(669, 14, 40)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(670, 14, 41)})], location: new SourceLocation(671, 14, 42)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(672, 14, 43)})], location: new SourceLocation(673, 14, 44)}),
    new Token(TokenType.String, "'b'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(677, 14, 48)})], location: new SourceLocation(678, 14, 49)}),
    new Token(TokenType.Reserved, "ELSE", { keyword: Keyword.ELSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(681, 14, 52)})], location: new SourceLocation(682, 14, 53)}),
    new Token(TokenType.String, "'c'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(686, 14, 57)})], location: new SourceLocation(687, 14, 58)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(690, 14, 61)})], location: new SourceLocation(691, 14, 62)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(694, 14, 65)})], location: new SourceLocation(695, 14, 66)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(697, 14, 68)})], location: new SourceLocation(698, 14, 69)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(699, 14, 70)})], location: new SourceLocation(700, 14, 71)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(704, 14, 75)})], location: new SourceLocation(705, 14, 76)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(710, 14, 81)})], location: new SourceLocation(709, 14, 80)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(711, 15, 1)}),
    new Token(TokenType.Reserved, "DISTINCT", { keyword: Keyword.DISTINCT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(717, 15, 7)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(726, 15, 16)})], location: new SourceLocation(718, 15, 8)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(727, 16, 1)})], location: new SourceLocation(729, 16, 3)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(730, 16, 4)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(732, 16, 6)})], location: new SourceLocation(731, 16, 5)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(737, 17, 5)})], location: new SourceLocation(733, 17, 1)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(738, 18, 1)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(741, 18, 4)})], location: new SourceLocation(740, 18, 3)}),
    new Token(TokenType.Reserved, "CROSS", { keyword: Keyword.CROSS, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(742, 19, 1)})], location: new SourceLocation(744, 19, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(749, 19, 8)})], location: new SourceLocation(750, 19, 9)}),
    new Token(TokenType.Identifier, "b", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(754, 19, 13)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(756, 19, 15)})], location: new SourceLocation(755, 19, 14)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(757, 20, 1)})], location: new SourceLocation(759, 20, 3)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(763, 20, 7)})], location: new SourceLocation(764, 20, 8)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(765, 20, 9)})], location: new SourceLocation(766, 20, 10)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(768, 20, 12)})], location: new SourceLocation(769, 20, 13)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(770, 20, 14)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(772, 20, 16)})], location: new SourceLocation(771, 20, 15)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(773, 20, 17)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(774, 20, 18)})], location: new SourceLocation(775, 20, 19)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(776, 20, 20)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(778, 20, 22)})], location: new SourceLocation(777, 20, 21)}),
    new Token(TokenType.Reserved, "INNER", { keyword: Keyword.INNER, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(779, 21, 1)})], location: new SourceLocation(781, 21, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(786, 21, 8)})], location: new SourceLocation(787, 21, 9)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(791, 21, 13)})], location: new SourceLocation(792, 21, 14)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(794, 21, 16)})], location: new SourceLocation(795, 21, 17)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(797, 21, 19)})], location: new SourceLocation(798, 21, 20)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(800, 21, 22)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(802, 21, 24)})], location: new SourceLocation(801, 21, 23)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(803, 21, 25)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(804, 21, 26)})], location: new SourceLocation(805, 21, 27)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(806, 21, 28)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(808, 21, 30)})], location: new SourceLocation(807, 21, 29)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(809, 22, 1)})], location: new SourceLocation(811, 22, 3)}),
    new Token(TokenType.Reserved, "INNER", { keyword: Keyword.INNER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(818, 22, 10)})], location: new SourceLocation(819, 22, 11)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(824, 22, 16)})], location: new SourceLocation(825, 22, 17)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(829, 22, 21)})], location: new SourceLocation(830, 22, 22)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(832, 22, 24)})], location: new SourceLocation(833, 22, 25)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(835, 22, 27)})], location: new SourceLocation(836, 22, 28)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(838, 22, 30)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(840, 22, 32)})], location: new SourceLocation(839, 22, 31)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(841, 22, 33)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(842, 22, 34)})], location: new SourceLocation(843, 22, 35)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(844, 22, 36)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(846, 22, 38)})], location: new SourceLocation(845, 22, 37)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(847, 23, 1)})], location: new SourceLocation(849, 23, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(853, 23, 7)})], location: new SourceLocation(854, 23, 8)}),
    new Token(TokenType.Identifier, "d", { keyword: Keyword.D, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(858, 23, 12)})], location: new SourceLocation(859, 23, 13)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(860, 23, 14)})], location: new SourceLocation(861, 23, 15)}),
    new Token(TokenType.Identifier, "d", { keyword: Keyword.D, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(863, 23, 17)})], location: new SourceLocation(864, 23, 18)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(865, 23, 19)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(867, 23, 21)})], location: new SourceLocation(866, 23, 20)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(868, 23, 22)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(869, 23, 23)})], location: new SourceLocation(870, 23, 24)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(871, 23, 25)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(873, 23, 27)})], location: new SourceLocation(872, 23, 26)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(874, 24, 1)})], location: new SourceLocation(876, 24, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(880, 24, 7)})], location: new SourceLocation(881, 24, 8)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(886, 24, 13)})], location: new SourceLocation(887, 24, 14)}),
    new Token(TokenType.Identifier, "d1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(891, 24, 18)})], location: new SourceLocation(892, 24, 19)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(894, 24, 21)})], location: new SourceLocation(895, 24, 22)}),
    new Token(TokenType.Identifier, "d1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(897, 24, 24)})], location: new SourceLocation(898, 24, 25)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(900, 24, 27)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(902, 24, 29)})], location: new SourceLocation(901, 24, 28)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(903, 24, 30)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(904, 24, 31)})], location: new SourceLocation(905, 24, 32)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(906, 24, 33)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(908, 24, 35)})], location: new SourceLocation(907, 24, 34)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(909, 25, 1)})], location: new SourceLocation(911, 25, 3)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(918, 25, 10)})], location: new SourceLocation(919, 25, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(923, 25, 15)})], location: new SourceLocation(924, 25, 16)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(929, 25, 21)})], location: new SourceLocation(930, 25, 22)}),
    new Token(TokenType.Identifier, "d2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(934, 25, 26)})], location: new SourceLocation(935, 25, 27)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(937, 25, 29)})], location: new SourceLocation(938, 25, 30)}),
    new Token(TokenType.Identifier, "d2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(940, 25, 32)})], location: new SourceLocation(941, 25, 33)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(943, 25, 35)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(945, 25, 37)})], location: new SourceLocation(944, 25, 36)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(946, 25, 38)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(947, 25, 39)})], location: new SourceLocation(948, 25, 40)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(949, 25, 41)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(951, 25, 43)})], location: new SourceLocation(950, 25, 42)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(952, 26, 1)})], location: new SourceLocation(954, 26, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(959, 26, 8)})], location: new SourceLocation(960, 26, 9)}),
    new Token(TokenType.Identifier, "e", { keyword: Keyword.E, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(964, 26, 13)})], location: new SourceLocation(965, 26, 14)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(966, 26, 15)})], location: new SourceLocation(967, 26, 16)}),
    new Token(TokenType.Identifier, "e", { keyword: Keyword.E, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(969, 26, 18)})], location: new SourceLocation(970, 26, 19)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(971, 26, 20)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(973, 26, 22)})], location: new SourceLocation(972, 26, 21)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(974, 26, 23)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(975, 26, 24)})], location: new SourceLocation(976, 26, 25)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(977, 26, 26)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(979, 26, 28)})], location: new SourceLocation(978, 26, 27)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(980, 27, 1)})], location: new SourceLocation(982, 27, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(987, 27, 8)})], location: new SourceLocation(988, 27, 9)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(993, 27, 14)})], location: new SourceLocation(994, 27, 15)}),
    new Token(TokenType.Identifier, "e1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(998, 27, 19)})], location: new SourceLocation(999, 27, 20)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1001, 27, 22)})], location: new SourceLocation(1002, 27, 23)}),
    new Token(TokenType.Identifier, "e1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1004, 27, 25)})], location: new SourceLocation(1005, 27, 26)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1007, 27, 28)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1009, 27, 30)})], location: new SourceLocation(1008, 27, 29)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1010, 27, 31)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1011, 27, 32)})], location: new SourceLocation(1012, 27, 33)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1013, 27, 34)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1015, 27, 36)})], location: new SourceLocation(1014, 27, 35)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1016, 28, 1)})], location: new SourceLocation(1018, 28, 3)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1025, 28, 10)})], location: new SourceLocation(1026, 28, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1031, 28, 16)})], location: new SourceLocation(1032, 28, 17)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1037, 28, 22)})], location: new SourceLocation(1038, 28, 23)}),
    new Token(TokenType.Identifier, "e2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1042, 28, 27)})], location: new SourceLocation(1043, 28, 28)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1045, 28, 30)})], location: new SourceLocation(1046, 28, 31)}),
    new Token(TokenType.Identifier, "e2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1048, 28, 33)})], location: new SourceLocation(1049, 28, 34)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1051, 28, 36)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1053, 28, 38)})], location: new SourceLocation(1052, 28, 37)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1054, 28, 39)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1055, 28, 40)})], location: new SourceLocation(1056, 28, 41)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1057, 28, 42)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1059, 28, 44)})], location: new SourceLocation(1058, 28, 43)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1060, 29, 1)})], location: new SourceLocation(1062, 29, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1066, 29, 7)})], location: new SourceLocation(1067, 29, 8)}),
    new Token(TokenType.Identifier, "f", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1071, 29, 12)})], location: new SourceLocation(1072, 29, 13)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1073, 29, 14)})], location: new SourceLocation(1074, 29, 15)}),
    new Token(TokenType.Identifier, "f", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1076, 29, 17)})], location: new SourceLocation(1077, 29, 18)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1078, 29, 19)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1080, 29, 21)})], location: new SourceLocation(1079, 29, 20)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1081, 29, 22)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1082, 29, 23)})], location: new SourceLocation(1083, 29, 24)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1084, 29, 25)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1086, 29, 27)})], location: new SourceLocation(1085, 29, 26)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1087, 30, 1)})], location: new SourceLocation(1089, 30, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1093, 30, 7)})], location: new SourceLocation(1094, 30, 8)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1099, 30, 13)})], location: new SourceLocation(1100, 30, 14)}),
    new Token(TokenType.Identifier, "f1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1104, 30, 18)})], location: new SourceLocation(1105, 30, 19)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1107, 30, 21)})], location: new SourceLocation(1108, 30, 22)}),
    new Token(TokenType.Identifier, "f1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1110, 30, 24)})], location: new SourceLocation(1111, 30, 25)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1113, 30, 27)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1115, 30, 29)})], location: new SourceLocation(1114, 30, 28)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1116, 30, 30)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1117, 30, 31)})], location: new SourceLocation(1118, 30, 32)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1119, 30, 33)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1121, 30, 35)})], location: new SourceLocation(1120, 30, 34)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1122, 31, 1)})], location: new SourceLocation(1124, 31, 3)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1131, 31, 10)})], location: new SourceLocation(1132, 31, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1136, 31, 15)})], location: new SourceLocation(1137, 31, 16)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1142, 31, 21)})], location: new SourceLocation(1143, 31, 22)}),
    new Token(TokenType.Identifier, "f2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1147, 31, 26)})], location: new SourceLocation(1148, 31, 27)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1150, 31, 29)})], location: new SourceLocation(1151, 31, 30)}),
    new Token(TokenType.Identifier, "f2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1153, 31, 32)})], location: new SourceLocation(1154, 31, 33)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1156, 31, 35)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1158, 31, 37)})], location: new SourceLocation(1157, 31, 36)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1159, 31, 38)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1160, 31, 39)})], location: new SourceLocation(1161, 31, 40)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1162, 31, 41)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1164, 31, 43)})], location: new SourceLocation(1163, 31, 42)}),
    new Token(TokenType.Reserved, "LIMIT", { keyword: Keyword.LIMIT, location: new SourceLocation(1165, 32, 1)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1170, 32, 6)})], location: new SourceLocation(1171, 32, 7)}),
    new Token(TokenType.Identifier, "OFFSET", { keyword: Keyword.OFFSET, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1172, 32, 8)})], location: new SourceLocation(1173, 32, 9)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1179, 32, 15)})], location: new SourceLocation(1180, 32, 16)}),
    new Token(TokenType.EoF, "", { eos: true, location: new SourceLocation(1181, 32, 17)})
]
