import { SourceLocation, Token, TokenType, Keyword } from "../../../src/lexer"

export default [
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(0, 1, 0)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(6, 1, 6)})], location: new SourceLocation(7, 1, 7)}),
    new Token(TokenType.Operator, "+", { location: new SourceLocation(8, 1, 8)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(9, 1, 9)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(10, 1, 10)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(11, 1, 11)}),
    new Token(TokenType.Comma, ",", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(13, 1, 13)})], location: new SourceLocation(12, 1, 12)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(14, 1, 14)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(15, 1, 15)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(16, 1, 16)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(17, 1, 17)}),
    new Token(TokenType.Operator, "/", { location: new SourceLocation(18, 1, 18)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(19, 1, 19)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(20, 1, 20)})], location: new SourceLocation(21, 1, 21)}),
    new Token(TokenType.Comma, ",", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(24, 1, 24)})], location: new SourceLocation(23, 1, 23)}),
    new Token(TokenType.Operator, "+", { location: new SourceLocation(25, 1, 25)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(26, 1, 26)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(27, 1, 27)}),
    new Token(TokenType.Numeric, "2", { location: new SourceLocation(28, 1, 28)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(29, 1, 29)}),
    new Token(TokenType.Numeric, "3", { location: new SourceLocation(30, 1, 30)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(31, 1, 31)})], location: new SourceLocation(32, 1, 32)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(34, 1, 34)})], location: new SourceLocation(35, 1, 35)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(38, 1, 38)})], location: new SourceLocation(37, 1, 37)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(39, 2, 1)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(45, 2, 7)})], location: new SourceLocation(46, 2, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(48, 2, 10)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(53, 2, 15)})], location: new SourceLocation(49, 2, 11)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(54, 2, 16)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(61, 2, 23)})], location: new SourceLocation(55, 2, 17)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(62, 2, 24)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(63, 2, 25)})], location: new SourceLocation(64, 2, 26)}),
    new Token(TokenType.Identifier, "sample", { keyword: Keyword.SAMPLE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(68, 2, 30)})], location: new SourceLocation(69, 2, 31)}),
    new Token(TokenType.RightParen, ")", { location: new SourceLocation(75, 2, 37)}),
    new Token(TokenType.Reserved, "GROUP", { keyword: Keyword.GROUP, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(76, 2, 38)})], location: new SourceLocation(77, 2, 39)}),
    new Token(TokenType.Identifier, "BY", { keyword: Keyword.BY, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(82, 2, 44)})], location: new SourceLocation(83, 2, 45)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(85, 2, 47)})], location: new SourceLocation(86, 2, 48)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(89, 2, 51)})], location: new SourceLocation(88, 2, 50)}),
    new Token(TokenType.Identifier, "WITH", { keyword: Keyword.WITH, location: new SourceLocation(90, 3, 1)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(94, 3, 5)})], location: new SourceLocation(95, 3, 6)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(96, 3, 7)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(99, 3, 10)})], location: new SourceLocation(97, 3, 8)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(100, 3, 11)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(101, 3, 12)}),
    new Token(TokenType.Identifier, "s", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(107, 3, 18)})], location: new SourceLocation(108, 3, 19)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(109, 3, 20)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(110, 3, 21)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(111, 3, 22)})], location: new SourceLocation(112, 3, 23)}),
    new Token(TokenType.Identifier, "sample", { keyword: Keyword.SAMPLE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(116, 3, 27)})], location: new SourceLocation(117, 3, 28)}),
    new Token(TokenType.Identifier, "s", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(123, 3, 34)})], location: new SourceLocation(124, 3, 35)}),
    new Token(TokenType.RightParen, ")", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(126, 3, 37)})], location: new SourceLocation(125, 3, 36)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(133, 4, 7)})], location: new SourceLocation(127, 4, 1)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(134, 4, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(135, 4, 9)})], location: new SourceLocation(136, 4, 10)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(140, 4, 14)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(142, 4, 16)})], location: new SourceLocation(141, 4, 15)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, location: new SourceLocation(143, 5, 1)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(148, 5, 6)})], location: new SourceLocation(149, 5, 7)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(150, 5, 8)}),
    new Token(TokenType.Identifier, "col1", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(155, 5, 13)})], location: new SourceLocation(151, 5, 9)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(156, 5, 14)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(157, 5, 15)})], location: new SourceLocation(158, 5, 16)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(159, 5, 17)})], location: new SourceLocation(160, 5, 18)}),
    new Token(TokenType.Reserved, "NOT", { keyword: Keyword.NOT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(163, 5, 21)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(167, 5, 25)})], location: new SourceLocation(164, 5, 22)}),
    new Token(TokenType.LeftParen, "(", { location: new SourceLocation(168, 5, 26)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(169, 5, 27)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(170, 5, 28)}),
    new Token(TokenType.Identifier, "col2", { location: new SourceLocation(171, 5, 29)}),
    new Token(TokenType.Reserved, "NOT", { keyword: Keyword.NOT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(175, 5, 33)})], location: new SourceLocation(176, 5, 34)}),
    new Token(TokenType.Identifier, "LIKE", { keyword: Keyword.LIKE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(179, 5, 37)})], location: new SourceLocation(180, 5, 38)}),
    new Token(TokenType.String, "'%x%'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(184, 5, 42)})], location: new SourceLocation(185, 5, 43)}),
    new Token(TokenType.Reserved, "OR", { keyword: Keyword.OR, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(190, 5, 48)})], location: new SourceLocation(191, 5, 49)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(193, 5, 51)})], location: new SourceLocation(194, 5, 52)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(195, 5, 53)}),
    new Token(TokenType.Identifier, "col2", { location: new SourceLocation(196, 5, 54)}),
    new Token(TokenType.Reserved, "IS", { keyword: Keyword.IS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(200, 5, 58)})], location: new SourceLocation(201, 5, 59)}),
    new Token(TokenType.Reserved, "NULL", { keyword: Keyword.NULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(203, 5, 61)})], location: new SourceLocation(204, 5, 62)}),
    new Token(TokenType.RightParen, ")", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(209, 5, 67)})], location: new SourceLocation(208, 5, 66)}),
    new Token(TokenType.Reserved, "ORDER", { keyword: Keyword.ORDER, location: new SourceLocation(210, 6, 1)}),
    new Token(TokenType.Identifier, "BY", { keyword: Keyword.BY, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(215, 6, 6)})], location: new SourceLocation(216, 6, 7)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(218, 6, 9)})], location: new SourceLocation(219, 6, 10)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(220, 6, 11)}),
    new Token(TokenType.Identifier, "col3", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(225, 6, 16)})], location: new SourceLocation(221, 6, 12)}),
    new Token(TokenType.Reserved, "LIMIT", { keyword: Keyword.LIMIT, location: new SourceLocation(226, 7, 1)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(231, 7, 6)})], location: new SourceLocation(232, 7, 7)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(234, 7, 9)})], location: new SourceLocation(233, 7, 8)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(241, 8, 7)})], location: new SourceLocation(235, 8, 1)}),
    new Token(TokenType.Operator, "*", { location: new SourceLocation(242, 8, 8)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(243, 8, 9)})], location: new SourceLocation(244, 8, 10)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(248, 8, 14)})], location: new SourceLocation(249, 8, 15)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(250, 8, 16)}),
    new Token(TokenType.Identifier, "main", { keyword: Keyword.MAIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(251, 8, 17)})], location: new SourceLocation(252, 8, 18)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(256, 8, 22)}),
    new Token(TokenType.Identifier, "b", { location: new SourceLocation(257, 8, 23)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(258, 8, 24)})], location: new SourceLocation(259, 8, 25)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(260, 8, 26)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(261, 8, 27)})], location: new SourceLocation(262, 8, 28)}),
    new Token(TokenType.Reserved, "as", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(263, 8, 29)})], location: new SourceLocation(264, 8, 30)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(266, 8, 32)})], location: new SourceLocation(267, 8, 33)}),
    new Token(TokenType.Reserved, "WHERE", { keyword: Keyword.WHERE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(268, 8, 34)})], location: new SourceLocation(269, 8, 35)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(274, 8, 40)})], location: new SourceLocation(275, 8, 41)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(276, 8, 42)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(278, 8, 44)})], location: new SourceLocation(277, 8, 43)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(279, 8, 45)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(280, 8, 46)})], location: new SourceLocation(281, 8, 47)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(282, 8, 48)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(283, 8, 49)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(284, 8, 50)})], location: new SourceLocation(285, 8, 51)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(288, 8, 54)})], location: new SourceLocation(289, 8, 55)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(290, 8, 56)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(292, 8, 58)})], location: new SourceLocation(291, 8, 57)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(293, 8, 59)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(294, 8, 60)})], location: new SourceLocation(295, 8, 61)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(296, 8, 62)}),
    new Token(TokenType.Identifier, "x", { location: new SourceLocation(297, 8, 63)}),
    new Token(TokenType.Reserved, "AND", { keyword: Keyword.AND, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(298, 8, 64)})], location: new SourceLocation(299, 8, 65)}),
    new Token(TokenType.Identifier, "y", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(302, 8, 68)})], location: new SourceLocation(303, 8, 69)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(304, 8, 70)}),
    new Token(TokenType.Identifier, "y", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(306, 8, 72)})], location: new SourceLocation(305, 8, 71)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(307, 8, 73)}),
    new Token(TokenType.Numeric, "0", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(308, 8, 74)})], location: new SourceLocation(309, 8, 75)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(311, 8, 77)})], location: new SourceLocation(310, 8, 76)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(318, 9, 7)})], location: new SourceLocation(312, 9, 1)}),
    new Token(TokenType.Operator, "-", { location: new SourceLocation(319, 9, 8)}),
    new Token(TokenType.Numeric, "1", { location: new SourceLocation(320, 9, 9)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(321, 9, 10)}),
    new Token(TokenType.Identifier, "TRUE", { keyword: Keyword.TRUE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(322, 9, 11)})], location: new SourceLocation(323, 9, 12)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(327, 9, 16)}),
    new Token(TokenType.Identifier, "FALSE", { keyword: Keyword.FALSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(328, 9, 17)})], location: new SourceLocation(329, 9, 18)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(334, 9, 23)}),
    new Token(TokenType.Reserved, "NULL", { keyword: Keyword.NULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(335, 9, 24)})], location: new SourceLocation(336, 9, 25)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(340, 9, 29)}),
    new Token(TokenType.Reserved, "CURRENT_TIME", { keyword: Keyword.CURRENT_TIME, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(341, 9, 30)})], location: new SourceLocation(342, 9, 31)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(354, 9, 43)}),
    new Token(TokenType.Reserved, "CURRENT_DATE", { keyword: Keyword.CURRENT_DATE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(355, 9, 44)})], location: new SourceLocation(356, 9, 45)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(368, 9, 57)}),
    new Token(TokenType.Reserved, "CURRENT_TIMESTAMP", { keyword: Keyword.CURRENT_TIMESTAMP, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(369, 9, 58)})], location: new SourceLocation(370, 9, 59)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(387, 9, 76)}),
    new Token(TokenType.String, "'aaa'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(388, 9, 77)})], location: new SourceLocation(389, 9, 78)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(394, 9, 83)}),
    new Token(TokenType.Identifier, "\"aaa\"", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(395, 9, 84)})], location: new SourceLocation(396, 9, 85)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(401, 9, 90)}),
    new Token(TokenType.Blob, "x'53514C697465'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(402, 9, 91)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(418, 9, 107)})], location: new SourceLocation(403, 9, 92)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(420, 9, 109)})], location: new SourceLocation(419, 9, 108)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(421, 10, 1)}),
    new Token(TokenType.BindVariable, "?1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(427, 10, 7)})], location: new SourceLocation(428, 10, 8)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(430, 10, 10)}),
    new Token(TokenType.BindVariable, "?", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(431, 10, 11)})], location: new SourceLocation(432, 10, 12)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(433, 10, 13)}),
    new Token(TokenType.BindVariable, ":param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(434, 10, 14)})], location: new SourceLocation(435, 10, 15)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(441, 10, 21)}),
    new Token(TokenType.BindVariable, "@param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(442, 10, 22)})], location: new SourceLocation(443, 10, 23)}),
    new Token(TokenType.Comma, ",", { location: new SourceLocation(449, 10, 29)}),
    new Token(TokenType.BindVariable, "$param", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(450, 10, 30)})], location: new SourceLocation(451, 10, 31)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(458, 10, 38)})], location: new SourceLocation(457, 10, 37)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(459, 11, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(465, 11, 7)})], location: new SourceLocation(466, 11, 8)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(470, 11, 12)})], location: new SourceLocation(471, 11, 13)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(472, 11, 14)})], location: new SourceLocation(473, 11, 15)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(477, 11, 19)})], location: new SourceLocation(478, 11, 20)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(479, 11, 21)})], location: new SourceLocation(480, 11, 22)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(484, 11, 26)})], location: new SourceLocation(485, 11, 27)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(488, 11, 30)})], location: new SourceLocation(489, 11, 31)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(492, 11, 34)})], location: new SourceLocation(493, 11, 35)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(494, 11, 36)})], location: new SourceLocation(495, 11, 37)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(499, 11, 41)})], location: new SourceLocation(500, 11, 42)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(505, 11, 47)})], location: new SourceLocation(504, 11, 46)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(506, 12, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(512, 12, 7)})], location: new SourceLocation(513, 12, 8)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(517, 12, 12)})], location: new SourceLocation(518, 12, 13)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(519, 12, 14)})], location: new SourceLocation(520, 12, 15)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(524, 12, 19)})], location: new SourceLocation(525, 12, 20)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(526, 12, 21)})], location: new SourceLocation(527, 12, 22)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(531, 12, 26)})], location: new SourceLocation(532, 12, 27)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(535, 12, 30)})], location: new SourceLocation(536, 12, 31)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(540, 12, 35)})], location: new SourceLocation(541, 12, 36)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(542, 12, 37)})], location: new SourceLocation(543, 12, 38)}),
    new Token(TokenType.String, "'b'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(547, 12, 42)})], location: new SourceLocation(548, 12, 43)}),
    new Token(TokenType.Reserved, "ELSE", { keyword: Keyword.ELSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(551, 12, 46)})], location: new SourceLocation(552, 12, 47)}),
    new Token(TokenType.String, "'c'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(556, 12, 51)})], location: new SourceLocation(557, 12, 52)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(560, 12, 55)})], location: new SourceLocation(561, 12, 56)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(564, 12, 59)})], location: new SourceLocation(565, 12, 60)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(566, 12, 61)})], location: new SourceLocation(567, 12, 62)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(571, 12, 66)})], location: new SourceLocation(572, 12, 67)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(577, 12, 72)})], location: new SourceLocation(576, 12, 71)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(578, 13, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(584, 13, 7)})], location: new SourceLocation(585, 13, 8)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(589, 13, 12)})], location: new SourceLocation(590, 13, 13)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(594, 13, 17)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(596, 13, 19)})], location: new SourceLocation(595, 13, 18)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(597, 13, 20)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(598, 13, 21)})], location: new SourceLocation(599, 13, 22)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(600, 13, 23)})], location: new SourceLocation(601, 13, 24)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(605, 13, 28)})], location: new SourceLocation(606, 13, 29)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(609, 13, 32)})], location: new SourceLocation(610, 13, 33)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(613, 13, 36)})], location: new SourceLocation(614, 13, 37)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(616, 13, 39)})], location: new SourceLocation(617, 13, 40)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(618, 13, 41)})], location: new SourceLocation(619, 13, 42)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(623, 13, 46)})], location: new SourceLocation(624, 13, 47)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(629, 13, 52)})], location: new SourceLocation(628, 13, 51)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(630, 14, 1)}),
    new Token(TokenType.Reserved, "CASE", { keyword: Keyword.CASE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(636, 14, 7)})], location: new SourceLocation(637, 14, 8)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(641, 14, 12)})], location: new SourceLocation(642, 14, 13)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(646, 14, 17)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(648, 14, 19)})], location: new SourceLocation(647, 14, 18)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(649, 14, 20)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(650, 14, 21)})], location: new SourceLocation(651, 14, 22)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(652, 14, 23)})], location: new SourceLocation(653, 14, 24)}),
    new Token(TokenType.String, "'a'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(657, 14, 28)})], location: new SourceLocation(658, 14, 29)}),
    new Token(TokenType.Reserved, "WHEN", { keyword: Keyword.WHEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(661, 14, 32)})], location: new SourceLocation(662, 14, 33)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(666, 14, 37)})], postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(668, 14, 39)})], location: new SourceLocation(667, 14, 38)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(669, 14, 40)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(670, 14, 41)})], location: new SourceLocation(671, 14, 42)}),
    new Token(TokenType.Reserved, "THEN", { keyword: Keyword.THEN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(672, 14, 43)})], location: new SourceLocation(673, 14, 44)}),
    new Token(TokenType.String, "'b'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(677, 14, 48)})], location: new SourceLocation(678, 14, 49)}),
    new Token(TokenType.Reserved, "ELSE", { keyword: Keyword.ELSE, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(681, 14, 52)})], location: new SourceLocation(682, 14, 53)}),
    new Token(TokenType.String, "'c'", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(686, 14, 57)})], location: new SourceLocation(687, 14, 58)}),
    new Token(TokenType.Identifier, "END", { keyword: Keyword.END, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(690, 14, 61)})], location: new SourceLocation(691, 14, 62)}),
    new Token(TokenType.Reserved, "AS", { keyword: Keyword.AS, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(694, 14, 65)})], location: new SourceLocation(695, 14, 66)}),
    new Token(TokenType.Identifier, "x", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(697, 14, 68)})], location: new SourceLocation(698, 14, 69)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(699, 14, 70)})], location: new SourceLocation(700, 14, 71)}),
    new Token(TokenType.Identifier, "test", { keyword: Keyword.TEST, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(704, 14, 75)})], location: new SourceLocation(705, 14, 76)}),
    new Token(TokenType.SemiColon, ";", { eos: true, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(710, 14, 81)})], location: new SourceLocation(709, 14, 80)}),
    new Token(TokenType.Reserved, "SELECT", { keyword: Keyword.SELECT, location: new SourceLocation(711, 15, 1)}),
    new Token(TokenType.Reserved, "DISTINCT", { keyword: Keyword.DISTINCT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(717, 15, 7)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(726, 15, 16)})], location: new SourceLocation(718, 15, 8)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(727, 16, 1)})], location: new SourceLocation(729, 16, 3)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(730, 16, 4)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(732, 16, 6)})], location: new SourceLocation(731, 16, 5)}),
    new Token(TokenType.Reserved, "FROM", { keyword: Keyword.FROM, postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(737, 17, 5)})], location: new SourceLocation(733, 17, 1)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(738, 18, 1)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(741, 18, 4)})], location: new SourceLocation(740, 18, 3)}),
    new Token(TokenType.Reserved, "CROSS", { keyword: Keyword.CROSS, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(742, 19, 1)})], location: new SourceLocation(744, 19, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(749, 19, 8)})], location: new SourceLocation(750, 19, 9)}),
    new Token(TokenType.Identifier, "b", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(754, 19, 13)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(756, 19, 15)})], location: new SourceLocation(755, 19, 14)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(757, 20, 1)})], location: new SourceLocation(759, 20, 3)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(763, 20, 7)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(765, 20, 9)})], location: new SourceLocation(764, 20, 8)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(766, 21, 1)})], location: new SourceLocation(770, 21, 5)}),
    new Token(TokenType.Identifier, "c", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(772, 21, 7)})], location: new SourceLocation(773, 21, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(774, 21, 9)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(776, 21, 11)})], location: new SourceLocation(775, 21, 10)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(777, 21, 12)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(778, 21, 13)})], location: new SourceLocation(779, 21, 14)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(780, 21, 15)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(782, 21, 17)})], location: new SourceLocation(781, 21, 16)}),
    new Token(TokenType.Reserved, "INNER", { keyword: Keyword.INNER, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(783, 22, 1)})], location: new SourceLocation(785, 22, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(790, 22, 8)})], location: new SourceLocation(791, 22, 9)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(795, 22, 13)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(798, 22, 16)})], location: new SourceLocation(796, 22, 14)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(799, 23, 1)})], location: new SourceLocation(803, 23, 5)}),
    new Token(TokenType.Identifier, "c1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(805, 23, 7)})], location: new SourceLocation(806, 23, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(808, 23, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(810, 23, 12)})], location: new SourceLocation(809, 23, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(811, 23, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(812, 23, 14)})], location: new SourceLocation(813, 23, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(814, 23, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(816, 23, 18)})], location: new SourceLocation(815, 23, 17)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(817, 24, 1)})], location: new SourceLocation(819, 24, 3)}),
    new Token(TokenType.Reserved, "INNER", { keyword: Keyword.INNER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(826, 24, 10)})], location: new SourceLocation(827, 24, 11)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(832, 24, 16)})], location: new SourceLocation(833, 24, 17)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(837, 24, 21)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(840, 24, 24)})], location: new SourceLocation(838, 24, 22)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(841, 25, 1)})], location: new SourceLocation(845, 25, 5)}),
    new Token(TokenType.Identifier, "c2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(847, 25, 7)})], location: new SourceLocation(848, 25, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(850, 25, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(852, 25, 12)})], location: new SourceLocation(851, 25, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(853, 25, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(854, 25, 14)})], location: new SourceLocation(855, 25, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(856, 25, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(858, 25, 18)})], location: new SourceLocation(857, 25, 17)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(859, 26, 1)})], location: new SourceLocation(861, 26, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(865, 26, 7)})], location: new SourceLocation(866, 26, 8)}),
    new Token(TokenType.Identifier, "d", { keyword: Keyword.D, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(870, 26, 12)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(872, 26, 14)})], location: new SourceLocation(871, 26, 13)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(873, 27, 1)})], location: new SourceLocation(877, 27, 5)}),
    new Token(TokenType.Identifier, "d", { keyword: Keyword.D, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(879, 27, 7)})], location: new SourceLocation(880, 27, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(881, 27, 9)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(883, 27, 11)})], location: new SourceLocation(882, 27, 10)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(884, 27, 12)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(885, 27, 13)})], location: new SourceLocation(886, 27, 14)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(887, 27, 15)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(889, 27, 17)})], location: new SourceLocation(888, 27, 16)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(890, 28, 1)})], location: new SourceLocation(892, 28, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(896, 28, 7)})], location: new SourceLocation(897, 28, 8)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(902, 28, 13)})], location: new SourceLocation(903, 28, 14)}),
    new Token(TokenType.Identifier, "d1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(907, 28, 18)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(910, 28, 21)})], location: new SourceLocation(908, 28, 19)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(911, 29, 1)})], location: new SourceLocation(915, 29, 5)}),
    new Token(TokenType.Identifier, "d1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(917, 29, 7)})], location: new SourceLocation(918, 29, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(920, 29, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(922, 29, 12)})], location: new SourceLocation(921, 29, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(923, 29, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(924, 29, 14)})], location: new SourceLocation(925, 29, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(926, 29, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(928, 29, 18)})], location: new SourceLocation(927, 29, 17)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(929, 30, 1)})], location: new SourceLocation(931, 30, 3)}),
    new Token(TokenType.Reserved, "LEFT", { keyword: Keyword.LEFT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(938, 30, 10)})], location: new SourceLocation(939, 30, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(943, 30, 15)})], location: new SourceLocation(944, 30, 16)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(949, 30, 21)})], location: new SourceLocation(950, 30, 22)}),
    new Token(TokenType.Identifier, "d2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(954, 30, 26)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(957, 30, 29)})], location: new SourceLocation(955, 30, 27)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(958, 31, 1)})], location: new SourceLocation(962, 31, 5)}),
    new Token(TokenType.Identifier, "d2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(964, 31, 7)})], location: new SourceLocation(965, 31, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(967, 31, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(969, 31, 12)})], location: new SourceLocation(968, 31, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(970, 31, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(971, 31, 14)})], location: new SourceLocation(972, 31, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(973, 31, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(975, 31, 18)})], location: new SourceLocation(974, 31, 17)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(976, 32, 1)})], location: new SourceLocation(978, 32, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(983, 32, 8)})], location: new SourceLocation(984, 32, 9)}),
    new Token(TokenType.Identifier, "e", { keyword: Keyword.E, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(988, 32, 13)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(990, 32, 15)})], location: new SourceLocation(989, 32, 14)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(991, 33, 1)})], location: new SourceLocation(995, 33, 5)}),
    new Token(TokenType.Identifier, "e", { keyword: Keyword.E, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(997, 33, 7)})], location: new SourceLocation(998, 33, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(999, 33, 9)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1001, 33, 11)})], location: new SourceLocation(1000, 33, 10)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1002, 33, 12)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1003, 33, 13)})], location: new SourceLocation(1004, 33, 14)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1005, 33, 15)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1007, 33, 17)})], location: new SourceLocation(1006, 33, 16)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1008, 34, 1)})], location: new SourceLocation(1010, 34, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1015, 34, 8)})], location: new SourceLocation(1016, 34, 9)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1021, 34, 14)})], location: new SourceLocation(1022, 34, 15)}),
    new Token(TokenType.Identifier, "e1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1026, 34, 19)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1029, 34, 22)})], location: new SourceLocation(1027, 34, 20)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(1030, 35, 1)})], location: new SourceLocation(1034, 35, 5)}),
    new Token(TokenType.Identifier, "e1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1036, 35, 7)})], location: new SourceLocation(1037, 35, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1039, 35, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1041, 35, 12)})], location: new SourceLocation(1040, 35, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1042, 35, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1043, 35, 14)})], location: new SourceLocation(1044, 35, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1045, 35, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1047, 35, 18)})], location: new SourceLocation(1046, 35, 17)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1048, 36, 1)})], location: new SourceLocation(1050, 36, 3)}),
    new Token(TokenType.Reserved, "RIGHT", { keyword: Keyword.RIGHT, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1057, 36, 10)})], location: new SourceLocation(1058, 36, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1063, 36, 16)})], location: new SourceLocation(1064, 36, 17)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1069, 36, 22)})], location: new SourceLocation(1070, 36, 23)}),
    new Token(TokenType.Identifier, "e2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1074, 36, 27)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1077, 36, 30)})], location: new SourceLocation(1075, 36, 28)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(1078, 37, 1)})], location: new SourceLocation(1082, 37, 5)}),
    new Token(TokenType.Identifier, "e2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1084, 37, 7)})], location: new SourceLocation(1085, 37, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1087, 37, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1089, 37, 12)})], location: new SourceLocation(1088, 37, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1090, 37, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1091, 37, 14)})], location: new SourceLocation(1092, 37, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1093, 37, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1095, 37, 18)})], location: new SourceLocation(1094, 37, 17)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1096, 38, 1)})], location: new SourceLocation(1098, 38, 3)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1102, 38, 7)})], location: new SourceLocation(1103, 38, 8)}),
    new Token(TokenType.Identifier, "f", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1107, 38, 12)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1109, 38, 14)})], location: new SourceLocation(1108, 38, 13)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(1110, 39, 1)})], location: new SourceLocation(1114, 39, 5)}),
    new Token(TokenType.Identifier, "f", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1116, 39, 7)})], location: new SourceLocation(1117, 39, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1118, 39, 9)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1120, 39, 11)})], location: new SourceLocation(1119, 39, 10)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1121, 39, 12)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1122, 39, 13)})], location: new SourceLocation(1123, 39, 14)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1124, 39, 15)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1126, 39, 17)})], location: new SourceLocation(1125, 39, 16)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1127, 40, 1)})], location: new SourceLocation(1129, 40, 3)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1133, 40, 7)})], location: new SourceLocation(1134, 40, 8)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1139, 40, 13)})], location: new SourceLocation(1140, 40, 14)}),
    new Token(TokenType.Identifier, "f1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1144, 40, 18)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1147, 40, 21)})], location: new SourceLocation(1145, 40, 19)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(1148, 41, 1)})], location: new SourceLocation(1152, 41, 5)}),
    new Token(TokenType.Identifier, "f1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1154, 41, 7)})], location: new SourceLocation(1155, 41, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1157, 41, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1159, 41, 12)})], location: new SourceLocation(1158, 41, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1160, 41, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1161, 41, 14)})], location: new SourceLocation(1162, 41, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1163, 41, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1165, 41, 18)})], location: new SourceLocation(1164, 41, 17)}),
    new Token(TokenType.Reserved, "NATURAL", { keyword: Keyword.NATURAL, preskips: [new Token(TokenType.WhiteSpace, "  ", { location: new SourceLocation(1166, 42, 1)})], location: new SourceLocation(1168, 42, 3)}),
    new Token(TokenType.Identifier, "FULL", { keyword: Keyword.FULL, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1175, 42, 10)})], location: new SourceLocation(1176, 42, 11)}),
    new Token(TokenType.Reserved, "OUTER", { keyword: Keyword.OUTER, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1180, 42, 15)})], location: new SourceLocation(1181, 42, 16)}),
    new Token(TokenType.Reserved, "JOIN", { keyword: Keyword.JOIN, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1186, 42, 21)})], location: new SourceLocation(1187, 42, 22)}),
    new Token(TokenType.Identifier, "f2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1191, 42, 26)})], postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1194, 42, 29)})], location: new SourceLocation(1192, 42, 27)}),
    new Token(TokenType.Reserved, "ON", { keyword: Keyword.ON, preskips: [new Token(TokenType.WhiteSpace, "    ", { location: new SourceLocation(1195, 43, 1)})], location: new SourceLocation(1199, 43, 5)}),
    new Token(TokenType.Identifier, "f2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1201, 43, 7)})], location: new SourceLocation(1202, 43, 8)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1204, 43, 10)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1206, 43, 12)})], location: new SourceLocation(1205, 43, 11)}),
    new Token(TokenType.Operator, "=", { location: new SourceLocation(1207, 43, 13)}),
    new Token(TokenType.Identifier, "a", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1208, 43, 14)})], location: new SourceLocation(1209, 43, 15)}),
    new Token(TokenType.Dot, ".", { location: new SourceLocation(1210, 43, 16)}),
    new Token(TokenType.Identifier, "x", { postskips: [new Token(TokenType.LineBreak, "\n", { location: new SourceLocation(1212, 43, 18)})], location: new SourceLocation(1211, 43, 17)}),
    new Token(TokenType.Reserved, "LIMIT", { keyword: Keyword.LIMIT, location: new SourceLocation(1213, 44, 1)}),
    new Token(TokenType.Numeric, "1", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1218, 44, 6)})], location: new SourceLocation(1219, 44, 7)}),
    new Token(TokenType.Identifier, "OFFSET", { keyword: Keyword.OFFSET, preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1220, 44, 8)})], location: new SourceLocation(1221, 44, 9)}),
    new Token(TokenType.Numeric, "2", { preskips: [new Token(TokenType.WhiteSpace, " ", { location: new SourceLocation(1227, 44, 15)})], location: new SourceLocation(1228, 44, 16)}),
    new Token(TokenType.SectionBreak, "", { eos: true, location: new SourceLocation(1229, 44, 17)})
]
